# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Misaka's Secrect Garden"
weight = 1

[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "Misaka的秘密花园"
weight = 2
