# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
customText = ""
since = 2020

[dateFormat]
lastUpdated = "Jan 02, 2006 15:04 MST"
published = "Jan 02, 2006"

[sidebar]
emoji = "🍥"
subtitle = "Misaka Study Notes."

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
math = false
readingTime = true

[article.license]
default = "Licensed under CC BY-NC-SA 4.0"
enabled = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
card = "summary_large_image"
site = ""

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
default = "auto"
toggle = true

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "utterances"

[comments.disqusjs]
admin = ""
adminLabel = ""
apiKey = ""
apiUrl = ""
shortname = ""

[comments.utterances]
issueTerm = "pathname"
label = "✨💬✨"
repo = "Moeomu/blog"

[comments.remark42]
host = ""
locale = ""
site = ""

[comments.vssue]
autoCreateIssue = false
clientId = ""
clientSecret = ""
owner = ""
platform = ""
repo = ""

[comments.waline]
avatar = "identicon"
emoji = [
  "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili",
  "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq",
  "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tieba",
  "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji",
  "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo",
]
lang = "en"
placeholder = ""
requiredMeta = ["nick", "mail"]
serverURL = ""
visitor = "true"

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
lang = ""
path = ""
region = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
category = ""
categoryID = ""
darkTheme = ""
emitMetadata = 0
lightTheme = ""
mapping = ""
reactionsEnabled = 1
repo = ""
repoID = ""

[comments.gitalk]
admin = ""
clientID = ""
clientSecret = ""
owner = ""
repo = ""

[comments.cusdis]
host = ""
id = ""
